config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end
  resources :users, only: [:index, :new, :create, :show] #create the 7 RESTful routes limiting it ONLY TO "get new" & "post create"
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end

  has_many :reviews
  has_many :users, through: :reviews

end

# un peu de vocabulaire...
# The Model Product
# holds the collection of all its instances.
# We usually store these objects (product) in an instance variable @products.
# notice the "S"

app/models/review.rb
class Review < ActiveRecord::Base
  validates :comment, :presence => true
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews
  has_many :products, through: :reviews

  validates :name, presence: true

end

# To Do/Read:
# http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :ensure_logged_in except:[:index]
  before_action :ensure_logged_in, only: [:edit, :create, :update, :destroy]

  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
        Product.all
    end

    @products = @products.order('products.created_at DESC').page(params[:page])

    # REPLACED BY respond_to:
    # if request.xhr?
    #   render @products
    # else
      # respond_to do |format|
      #   format.html {
      #     @product = Product.new
      #     render :index
      #   }
      #   format.js
      # end
    # end

      # note:--------------
      # format.html
      # is equivalent to:

      # format.html {
      #   render :index
      # }
      # ------------------

    respond_to do |format|
      format.html
      format.js
    end

  end


  def show
    @product = Product.find(params[:id])
    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :url)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, only: [:create, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    # Check out this article on [.build](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel)
    # You could use a longer alternate syntax if it makes more sense to you
    #
    # @review = Review.new(
    #   comment: params[:review][:comment],
    #   product_id: @product.id,
    #   user_id: current_user.id
    # )

    respond_to do |format|
        if @review.save
          format.html { redirect_to product_path(@product.id), notice: 'Review added.' }
          format.js {} # This will look for app/views/reviews/create.js.erb
        else
          format.html { render 'products/show', alert: 'There was an error.'  }
          format.js {} # This will look for app/views/reviews/create.js.erb
        end
      end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

# LEER ÉSTE CODIGO Y BUSCAR
# Action Controller: 7 Filters

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: "You are Logged in!"
    else
      flash.now[:alert] = "Invalid email or password!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out! See you soon!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Signed up successfully! Log in: to add, edit, and review products."
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private #STRONG PARAMS
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

# Questions:
# where is :user coming from ?


#THE ABOVE IS THE RESULT OF RUNNING (excluding what's inside each corresponding method):
#$ rails g controller users new create

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bazar</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <div class="container">
        <header>
          <h1 class="logo"><%= link_to 'Bazar', products_path %><em> Ouvert</em></h1>
          <p class="userinfo">
            <% if current_user %>
            Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
            <% else %>
            <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
            <% end %>
          </p>
        </header>

        <% if flash[:notice] %>
          <p id="notice"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:alert] %>
          <p id="alert"><%= flash[:alert] %></p>
        <% end %>

        <%= yield %>
      </div>
  </body>
</html>

<!-- review THIS! -->

<!-- FMI: This is a working user: -->
<!-- Login: user@remember.com
Password: password -->

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit value="Submit" %>
  </div>

<% end %>

<!--
Questions:
Where is full_messages ? => ERROR guides active record
TO Do/Read:
Active Record Validations and Callbacks: 7 Working with Validation Errors
-->

app/views/products/_product.html.erb
<!-- _product is <=> to @products.each do { ...} -->
  <li class="main-menu">
      <ul><p><%= link_to product.name, product_path(product.id) %> <%= product.description %> €<%= product.formatted_price %> <%= link_to '| Edit', edit_product_path(product.id) if current_user %> </p></ul>
  </li>

app/views/products/_review_form_errors.html.erb
<% if @review.errors.present? %>
  <% @review.errors.full_messages.each do |error| %>
    <div class="alert">
      <%= error %>
    </div>
  <% end %>
<% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <div class='review'>
    <div class='comment'>
      <p><%= review.comment %></p>
    </div>
    <% if review.user != nil %>
      <div class='poster'>
        <p> by <%= review.user.name %> on <%= review.created_at %></p>
      </div>
      <br />
    <% end %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<p>Rainforest is open market. Add, edit, review products and see who's part of the community!</p>
<nav>
  <%= link_to 'New Product', new_product_path %>
  <!-- renders a helpful message with numbers of displayed vs. total entries -->
  <h1><small><%= page_entries_info @products %></small></h1>

  <%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
  <% end %>

  <div id="products">
    <%= render @products %>
  </div>

  <!-- outputs several pagination links such as « First ‹ Prev ... 2 3 4 5 6 7 8 9 10 ... Next › Last » -->
  <%= paginate @products %>
</nav>

<br />

<% if current_user %>
  <!-- <h2>Welcome to your Forest!</h2> -->
  <!-- <p>Feel free to add a product to the list.</p> -->
  <!-- < render 'form' ><br /> -->
  <%= link_to 'Contact the community', users_path %>
<% end  %>

<!-- To READ:
Dynamic link to each product. => API LINK_TO. Google "Rails link_to" documentation -->

app/views/products/index.js.erb
<% if params[:search] && params[:page].nil? %>
  $('#products').html("<%= j(render @products) %>");
<% else %>
  $('#products').append('<%= j render(@products) %>');
<% end %>

$('.pagination').replaceWith('<%= j paginate(@products) %>');


// FYI:
// escape_javascript <=> j
//
// THIS VIEW DOES THE SAME AS:
// .done(function(data){
//    console.log(data);
//    $('#products').html(data);
//  });

app/views/products/new.html.erb
<h1>AdNew product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Your Product id# <%= @product.id %></h1>

<%= link_to 'Back to product list', products_path %>

<p><%= @product.name %>, <%= @product.description %></p>
<p>€<%= @product.formatted_price %></p>
<img src="<%= @product.url %>" height="300" width="300">
<p><%= link_to 'Edit this product', edit_product_path(@product) %></p>

<h3>Reviews</h3>

  <p>You are reading reviews for: <%= @product.name %></p>
  <br />

  <div id=review-list>
    <%= render :partial => "reviews" %>
  </div>

<% if current_user %>
  <h4>New Review</h4>

  <%= form_for [@product, @review], :remote => true do |f| %>
    <div id='review-form-errors'>
      <%= render :partial => "/products/review_form_errors" %>
    </div>

    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review to this product.</p>
<% end %>

<script type="text/javascript">
  $(function() {
     $("#new_review")
        .on('ajax:beforeSend', function() { // set this code to happen just before the ajax request is made
          $("input[type='submit']") // make changes to the submit button
            .val('Saving...') // change the text on the button
            .attr('disabled', 'disabled'); // disable the button
        })
        .on('ajax:complete', function() {
          $("input[type='submit']")
            .val('Create Review')
            .removeAttr('disabled');
        });
  });
</script>


<!--
To Do's:
Edit Link/Button
-->

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
// alert("I’m responding to your request!");
$("#review-list").html("<%= escape_javascript(render(:partial => 'products/reviews')) %>");

<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/index.html.erb
<h1>Currenly Rainforest's User list is</h1>

<% @users.each do |user| %>
  <ul>
    <li>Client id-nº<%= user.id %></li>
    <li><%= link_to user.name, user_path(user.id) %></li>
    <li><%= user.email %></li>
  </ul>

<% end %>

app/views/users/new.html.erb
<!-- <h1>Hey User, Sign Up</h1> -->

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <li>
          Form is invalid.
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>.
        </li>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit "sign in" %></div>

<% end %>

<!-- Questions:
Q: How to add a value of "Sign Up!" instead of "create user" when it seems we only have access to the form's div ?
R: The beauty of helper form is allowing you to enter the value of that rails version on input tag as shown in "sign in" at L31  -->

app/views/users/show.html.erb
<h1>Hello, Your're looking at User nº<%= @user.id %></h1>
<p>His/her name is: <%= @user.name %></p>
<p>Don't remember his/her email? It's ok, it's: <%= @user.email %></p>
<p>Get in contact, and make the best out of the community!</p>